-- Database Schema for Photography WebApp Migration to MySQL
-- Generated by AI Agent

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` enum('user','admin','editor') DEFAULT 'user',
  `phone` varchar(50),
  `status` enum('Active','Inactive') DEFAULT 'Active',
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Table structure for table `clients`
--

CREATE TABLE `clients` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(50) NOT NULL,
  `address` text,
  `city` varchar(100),
  `state` varchar(100),
  `zipCode` varchar(20),
  `category` enum('Regular','VIP','New Inquiry') DEFAULT 'New Inquiry',
  `tags` json DEFAULT NULL, -- Storing tags array as JSON
  `notes` text,
  `totalBilled` decimal(10,2) DEFAULT 0.00,
  `totalPaid` decimal(10,2) DEFAULT 0.00,
  `pendingAmount` decimal(10,2) DEFAULT 0.00,
  `event` varchar(255),
  `budget` decimal(10,2) DEFAULT 0.00,
  `status` enum('Lead','Active','Archived') DEFAULT 'Lead',
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Table structure for table `services`
--

CREATE TABLE `services` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` text,
  `category` enum('photography','video','drone','product','other') DEFAULT 'photography',
  `ratePerDay` decimal(10,2) NOT NULL,
  `ratePerUnit` decimal(10,2) DEFAULT 0.00,
  `isActive` tinyint(1) DEFAULT 1,
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Table structure for table `contacts`
--

CREATE TABLE `contacts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `message` text NOT NULL,
  `status` enum('New','Read','Replied') DEFAULT 'New',
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Table structure for table `enquiries`
--

CREATE TABLE `enquiries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `groomName` varchar(255) NOT NULL,
  `brideName` varchar(255) NOT NULL,
  `phoneNumber` varchar(50) NOT NULL,
  `eventStartDate` datetime NOT NULL,
  `eventEndDate` datetime NOT NULL,
  `events` json DEFAULT NULL, -- Array of strings
  `budget` decimal(10,2),
  `location` varchar(255) NOT NULL,
  `services` json DEFAULT NULL, -- Array of strings
  `message` text,
  `status` enum('New','Contacted','Booked','Closed') DEFAULT 'New',
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Table structure for table `films`
--

CREATE TABLE `films` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `youtubeUrl` varchar(255) NOT NULL,
  `category` varchar(100) DEFAULT 'Wedding',
  `status` enum('Active','Inactive') DEFAULT 'Active',
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Table structure for table `galleries`
--

CREATE TABLE `galleries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255),
  `image` varchar(255) NOT NULL,
  `category` varchar(100) DEFAULT 'General',
  `status` enum('Active','Inactive') DEFAULT 'Active',
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Table structure for table `sliders`
--

CREATE TABLE `sliders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `subtitle` varchar(255),
  `image` varchar(255) NOT NULL,
  `status` enum('Active','Inactive') DEFAULT 'Active',
  `displayOrder` int(11) DEFAULT 0,
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Table structure for table `testimonials`
--

CREATE TABLE `testimonials` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `coupleName` varchar(255) NOT NULL,
  `location` varchar(255),
  `thumbnail` varchar(255),
  `shortDescription` varchar(255) NOT NULL,
  `fullDescription` text,
  `rating` int(11) DEFAULT 5,
  `displayOrder` int(11) DEFAULT 0,
  `status` enum('Active','Inactive') DEFAULT 'Active',
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Table structure for table `love_stories`
--

CREATE TABLE `love_stories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `location` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `thumbnail` varchar(255) NOT NULL,
  `gallery` json DEFAULT NULL, -- Array of images
  `status` enum('Active','Inactive') DEFAULT 'Active',
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Table structure for table `orders`
--

CREATE TABLE `orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `whatsapp_no` varchar(50) NOT NULL,
  `email` varchar(255),
  `event_name` varchar(255),
  `photography_type` varchar(255),
  `location` varchar(255),
  `event_date` datetime,
  `event_end_date` datetime,
  `serviceConfig` json DEFAULT NULL,
  `start_time` varchar(50),
  `end_time` varchar(50),
  `service` varchar(255), -- Comma separated string
  `album_pages` varchar(50),
  `amount` decimal(10,2),
  `amount_paid` decimal(10,2),
  `remaining_amount` decimal(10,2),
  `deliverables` text,
  `delivery_date` datetime,
  `order_status` enum('Pending','In Progress','Delivered','Cancelled') DEFAULT 'Pending',
  `notes` text,
  `relatedUser_id` int(11),
  `client_id` int(11),
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`relatedUser_id`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Table structure for table `quotations`
--

CREATE TABLE `quotations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `quotationNumber` varchar(50) NOT NULL,
  `client_id` int(11),
  `eventType` enum('Wedding','Pre-wedding','Other') NOT NULL,
  `quotationDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `eventDate` datetime NOT NULL,
  `validityDate` datetime NOT NULL,
  `subtotal` decimal(10,2) NOT NULL,
  `discount` decimal(10,2) DEFAULT 0.00,
  `discountType` enum('fixed','percentage') DEFAULT 'fixed',
  `taxPercentage` decimal(5,2) DEFAULT 0.00,
  `tax` decimal(10,2) DEFAULT 0.00,
  `grandTotal` decimal(10,2) NOT NULL,
  `paymentTerms` text,
  `notes` text,
  `thankYouMessage` text,
  `status` enum('Draft','Sent','Accepted','Rejected','Expired','Negotiation') DEFAULT 'Draft',
  `clientName` varchar(255),
  `location` varchar(255),
  `retainerAmount` decimal(10,2) DEFAULT 0.00,
  `stage` varchar(50) DEFAULT 'Concept',
  `deliverables` json DEFAULT NULL,
  `moodboard` varchar(255),
  `channel` enum('Email','WhatsApp','Call','Other') DEFAULT 'Email',
  `followUpDate` datetime,
  `convertedToInvoice` tinyint(1) DEFAULT 0,
  `invoice_id` int(11) DEFAULT NULL, -- Will create FK later to avoid circular dependency
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON DELETE SET NULL,
  UNIQUE KEY `quotationNumber` (`quotationNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Table structure for table `quotation_services` (Relation table for Quotation Items)
--

CREATE TABLE `quotation_services` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `quotation_id` int(11) NOT NULL,
  `service_id` int(11) NOT NULL,
  `serviceName` varchar(255),
  `quantity` int(11) DEFAULT 1,
  `days` int(11) DEFAULT 1,
  `ratePerDay` decimal(10,2) NOT NULL,
  `total` decimal(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`quotation_id`) REFERENCES `quotations`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`service_id`) REFERENCES `services`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Table structure for table `invoices`
--

CREATE TABLE `invoices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `invoiceNumber` varchar(50) NOT NULL,
  `client_id` int(11),
  `quotation_id` int(11),
  `eventType` varchar(255) NOT NULL,
  `invoiceDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `eventDate` datetime NOT NULL,
  `dueDate` datetime NOT NULL,
  `subtotal` decimal(10,2) DEFAULT 0.00,
  `discount` decimal(10,2) DEFAULT 0.00,
  `discountType` enum('fixed','percentage') DEFAULT 'fixed',
  `taxPercentage` decimal(5,2) DEFAULT 0.00,
  `tax` decimal(10,2) DEFAULT 0.00,
  `grandTotal` decimal(10,2) DEFAULT 0.00,
  `paymentStatus` enum('Paid','Partially Paid','Partial','Unpaid','Overdue','Draft','Sent') DEFAULT 'Unpaid',
  `amountPaid` decimal(10,2) DEFAULT 0.00,
  `workflowStage` varchar(50) DEFAULT 'Planning',
  `paymentMethod` varchar(50) DEFAULT 'UPI',
  `clientName` varchar(255),
  `bankAccountName` varchar(255),
  `bankAccountNumber` varchar(255),
  `bankIfscCode` varchar(50),
  `bankUpiId` varchar(100),
  `notes` text,
  `thankYouMessage` text,
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`quotation_id`) REFERENCES `quotations`(`id`) ON DELETE SET NULL,
  UNIQUE KEY `invoiceNumber` (`invoiceNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Update Quotation with Invoice ID FK
ALTER TABLE `quotations` ADD CONSTRAINT `fk_quotation_invoice` FOREIGN KEY (`invoice_id`) REFERENCES `invoices`(`id`) ON DELETE SET NULL;

--
-- Table structure for table `invoice_services`
--

CREATE TABLE `invoice_services` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `invoice_id` int(11) NOT NULL,
  `service_id` int(11) NOT NULL,
  `serviceName` varchar(255),
  `quantity` int(11) DEFAULT 1,
  `days` int(11) DEFAULT 1,
  `ratePerDay` decimal(10,2) NOT NULL,
  `total` decimal(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`invoice_id`) REFERENCES `invoices`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`service_id`) REFERENCES `services`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Table structure for table `payments`
--

CREATE TABLE `payments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `invoice_id` int(11) NOT NULL,
  `client_id` int(11) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `paymentDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `paymentMethod` enum('Cash','Bank Transfer','UPI','Credit Card','Cheque','Other') NOT NULL,
  `transactionId` varchar(255),
  `notes` text,
  `isRecorded` tinyint(1) DEFAULT 1,
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`invoice_id`) REFERENCES `invoices`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

COMMIT;
